[phases.setup]
cmds = ["apt-get update", "apt-get install -y libmagic1"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "python server.py"